// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc2619.BasketballBot2016.subsystems;
import edu.wpi.first.wpilibj.AnalogChannel;
import edu.wpi.first.wpilibj.CANJaguar;
import org.usfirst.frc2619.BasketballBot2016.RobotMap;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc2619.BasketballBot2016.Robot;
/**
 *
 */
public class TeeterTotterArm extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar rightMotor = RobotMap.teeterTotterArmRightMotor;
    CANJaguar leftMotor = RobotMap.teeterTotterArmLeftMotor;
    AnalogChannel armPot = RobotMap.teeterTotterArmArmPot;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void run(double speed) {
        Robot.teeterTotterArm.leftMotor.set(speed);
        Robot.teeterTotterArm.rightMotor.set(-speed);
    }
    
    public void stop() {
        Robot.teeterTotterArm.leftMotor.set(0);
        Robot.teeterTotterArm.rightMotor.set(0);
    }
}
